version: '3.9'
services:
  db:
    image: postgres:16
    container_name: poc-ab-db
    environment:
      POSTGRES_DB: dungeon
      POSTGRES_USER: dungeon
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dungeon -d dungeon"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
