spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dungeon
    username: dungeon
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

server:
  port: ${PORT:8080}

ab:
  split:
    a: ${AB_SPLIT_A:50}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha